### ISSUE TITLE
后台如果设置成发送邮件注册注册不可用

### ISSUE THREAD

**Issue by MageeLeon** [poisonboy/discuz#1]
![捕获](https://user-images.githubusercontent.com/45738758/83413995-51cd4480-a44f-11ea-90d0-6010dc29ae37.PNG)
![捕获2](https://user-images.githubusercontent.com/45738758/83414000-54c83500-a44f-11ea-85b6-667878c0b64c.PNG)
后台如果设置成发送邮件注册注册不可用，不会自动切换成邮件注册。

**Comment by poisonboy** [comment]
嗯 建议开启普通注册模式

**Comment by MageeLeon** [comment]
> 嗯 建议开启普通注册模式

看来暂时只能这样了 后期能有改善嘛~
